[package]
name = "fanta"
version = "0.1.5"
authors = ["Pete Mertz <peter.s.mertz@gmail.com>"]
description = "A middleware based http async web server."
readme = "README.md"
license = "MIT"
documentation = "https://github.com/trezm/fanta"
homepage = "https://github.com/trezm/fanta"
repository = "https://github.com/trezm/fanta"

[dependencies]
bytes = "0.4"
futures = "0.1.11"
httparse = "1.1.2"
lazy_static = "0.2"
log = "0.3.6"
net2 = "0.2"
regex = "0.2"
serde = "1.0.24"
serde_json = "1.0.8"
serde_derive = "1.0.24"
time = "0.1"
tokio-core = "0.1.0"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"

[dev-dependencies]
rustc-serialize = "0.3"
num_cpus = "1.0"
env_logger = { version = "0.3.4", default-features = false }
