[package]
name = "thruster-server"
version = "0.7.6"
authors = ["Pete Mertz <peter.s.mertz@gmail.com>"]
description = "The core future wrappers aroun the thruster web framework"
readme = "README.md"
license = "MIT"
keywords = ["thruster", "router", "fast", "http", "hyper"]
documentation = "https://docs.rs/thruster"
homepage = "https://thruster.pete.pm"
repository = "https://github.com/trezm/thruster"
edition = "2018"

[features]
thruster_async_await = []
hyper_server = [
  "hyper",
  "thruster-context/hyper_server"
]

[dependencies]
futures-legacy = { version = "0.1.23", package = "futures" }
hyper = { version = "0.12.25", optional = true }
net2 = "0.2"
num_cpus = "1.0"
tokio = { git = "https://github.com/tokio-rs/tokio", branch = "master" }
tokio-codec = { git = "https://github.com/tokio-rs/tokio", branch = "master" }
thruster-core = { version = "0.7", path = "../thruster-core" }
thruster-app = { version = "0.7", path = "../thruster-app" }
thruster-context = { version = "0.7", path = "../thruster-context" }
